# -*- coding: utf-8 -*-
"""Stock Market Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mN6szJCMiLnHIL6pXC4SaiWr4jdlG-fD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Collect historical stock market data
data = pd.read_csv('/content/drive/MyDrive/ML Files/AAPL.csv')
print(data.head(10))
#Clean and preprocess
#Drop rows with missing values
# Check for missing values
print(data.isnull().sum())

# Drop rows with missing values (if any)
data = data.dropna()

#Check the 'Date' column is in datetime format
data['Date'] = pd.to_datetime(data['Date'])

# Remove time component (if there are timestamps) and keep only the date
data['Date'] = data['Date'].dt.date


# Make the 'Date' column as the index
data.set_index('Date', inplace=True)

# Check the index is a datetime index
#data.index = pd.to_datetime(data.index)

# Display the cleaned data
print(data.head())

# Calculate moving averages
data['MA_20'] = data['Close'].rolling(window=20).mean()
data['MA_50'] = data['Close'].rolling(window=50).mean()

# Calculate daily returns
data['Daily_Return'] = data['Close'].pct_change()

# Calculate rolling volatility (standard deviation of daily returns)
data['Volatility'] = data['Daily_Return'].rolling(window=20).std()

# Set plot style
sns.set(style="whitegrid")

# Plot stock prices and moving averages
plt.figure(figsize=(14, 7))
plt.plot(data['Close'], label='Close Price', color='blue')
plt.plot(data['MA_20'], label='20-Day Moving Average', color='orange')
plt.plot(data['MA_50'], label='50-Day Moving Average', color='green')
plt.title('Stock Prices and Moving Averages')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend()
plt.show()

# Plot volatility
plt.figure(figsize=(14, 7))
plt.plot(data['Volatility'], label='20-Day Rolling Volatility', color='red')
plt.title('Stock Price Volatility')
plt.xlabel('Date')
plt.ylabel('Volatility')
plt.legend()
plt.show()



"""# New Section"""

